version: "3"
services:
  node:
    build: ./docker/node
    tty: true
    volumes:
      - .:/work
    working_dir: /work

  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=typescript
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - 13306:3306

volumes:
  db-store:
