name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_riverpod: ^2.0.2
  go_router: ^5.1.0
  grpc: ^3.0.2
  grpc_gen:
    path: ../grpc_gen

  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.0
  go_router_builder: ^1.0.14

flutter:

  uses-material-design: true
